services:
  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  showcase-app:
    image: rsa-showcase
    ports:
      - 80:8080
    depends_on:
      - redis
