server:
  port: 8080
  servlet:
    context-path: /
    address: localhost
    session:
      cookie:
        http-only: false
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
thymeleaf:
  prefix: classpath:templates/
  suffix: .html
  mode: HTML
  cache: false
crypto:
  primeNumberLength: 512